animal = "     ChanCHito feliz    "
print(animal.upper())
print(animal.lower())
print(animal.capitalize())
print(animal.title())
print(animal.strip())
print(animal.title().strip())
print(animal.rstrip())
print(animal.lstrip())
print(animal.find("cH"))
print(animal.replace("nCH", "j"))
print("nCH" in animal)
print("nCH" not in animal)